import "@/styles/globals.scss";

export default async function RootLayout(pageProps) {
  return (
    <html lang="en">
      <head>
        {/* ... */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css"
        ></link>
      </head>
      <body>
        <main className="container">{pageProps.children}</main>
      </body>
    </html>
  );
}


// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout(pageProps) {
//   return (
//     <html lang="en">
//       <head>
//         <link 
//           rel="stylesheet" 
//           href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css"
//         />
//       </head>
//       <body>
//         <main className="container">{pageProps.children}</main>
//       </body>
//     </html>
//   );
// }
